### ISSUE TITLE
Error when processing a feed

### ISSUE THREAD

**Issue by absentpendulum** [muchdogesec/obstracts#66]
I'm running into an issue when trying to process a feed, where it always fails to process them based on this error: 

```[2024-11-28 04:28:48,822: INFO/ForkPoolWorker-4] Task obstracts.cjob.tasks.process_post[f069cba2-dc95-46b1-a9b4-97f1cb3a49a8] succeeded in 0.6918897879986616s: 'afbb3ef0-9203-4e70-bd64-e02b087255b7'
celery-1      | [2024-11-28 04:28:48,824: INFO/MainProcess] Task obstracts.cjob.tasks.process_post[6dfbd077-e079-4984-9190-3e74a75e2d4f] received
celery-1      | [2024-11-28 04:28:48,839: INFO/ForkPoolWorker-4] running file2txt on Default Profile/afbb3ef0-9203-4e70-bd64-e02b087255b7/e76b918f-a839-53de-8e4f-f0bb09c4e178
celery-1      | [2024-11-28 04:28:48,882: INFO/ForkPoolWorker-4] running txt2stix on Default Profile/afbb3ef0-9203-4e70-bd64-e02b087255b7/e76b918f-a839-53de-8e4f-f0bb09c4e178
celery-1      | [2024-11-28 04:28:48,882: ERROR/ForkPoolWorker-4] failed to process post with id: e76b918f-a839-53de-8e4f-f0bb09c4e178
celery-1      | [2024-11-28 04:28:48,882: ERROR/ForkPoolWorker-4] unsupported operand type(s) for /: 'NoneType' and 'str'
celery-1      | Traceback (most recent call last):
celery-1      |   File "/usr/src/app/obstracts/cjob/tasks.py", line 168, in process_post
celery-1      |     processor.process()
celery-1      |   File "/usr/local/lib/python3.11/site-packages/dogesec_commons/stixifier/stixifier.py", line 126, in process
celery-1      |     bundler = self.txt2stix()
celery-1      |               ^^^^^^^^^^^^^^^
celery-1      |   File "/usr/local/lib/python3.11/site-packages/dogesec_commons/stixifier/stixifier.py", line 85, in txt2stix
celery-1      |     extractors = all_extractors(self.profile.extractions)
celery-1      |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-1      |   File "/usr/local/lib/python3.11/site-packages/dogesec_commons/stixifier/stixifier.py", line 28, in all_extractors
celery-1      |     extractors = txt2stix.extractions.parse_extraction_config(txt2stix.INCLUDES_PATH).values()
celery-1      |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-1      |   File "/usr/local/lib/python3.11/site-packages/txt2stix/extractions.py", line 44, in parse_extraction_config
celery-1      |     test_cases = load_test_cases_config(include_path)
celery-1      |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-1      |   File "/usr/local/lib/python3.11/site-packages/txt2stix/extractions.py", line 51, in load_test_cases_config
celery-1      |     config_file = include_path/'tests/test_cases.yaml'
celery-1      |                   ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
celery-1      | TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
```

Running this on an EC2 instance running Ubuntu 24.04.1 LTS with all services (vulmatch, ctibutler, history4feed, obstracts) being deployed in Docker. Any ideas on what could be causing this?

**Comment by himynamesdave** [comment]
We've just shipped some big updates to (h4f/obstracts). Can you rebuild them both and try this again?

On the face of it looks like you're trying AI extractions (we pull in example extractions for the AI prompt from `tests/test_cases.yaml`) and these were both overhauled in releases yesterday

If the problem persists, please post the body of the profile (GET Profiles) you're using when adding the feed.

**Comment by absentpendulum** [comment]
That looks to be all working now, thanks for the response!
